BeSpokedSalesApp/Controllers/CustomerController.cs
using BeSpokedSalesApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using BeSpokedSalesApp.Common;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BeSpokedSalesApp.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ILogger<CustomerController> _logger;
        private readonly ApiClient<Customer> _apiClient;
        private readonly string _apiEndpoint;
        public CustomerController(ILogger<CustomerController> logger, ApiClient<Customer> apiClient)
        {
            _apiClient = apiClient;
            _logger = logger;
        }

        public async Task<IActionResult> Customers()
        {
            var Customers = await _apiClient.GetAsync("Customers");
            var viewModel = new CustomerListModel { Customers = Customers };
            return View(viewModel);
        }

        public async Task<IActionResult> CreateCustomer()
        {
            CustomerCreateModel customerCreateModel = new CustomerCreateModel();
            return View(customerCreateModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCustomer(Customer Customer)
        {
            if (ModelState.IsValid)
            {
                await _apiClient.PostAsync("Customers", Customer);
                return RedirectToAction("Customers");

            }
            else
            {
                CustomerCreateModel customerCreateModel = new CustomerCreateModel()
                {
                    Customer = Customer
                };
                return View(customerCreateModel);
            }
        }
    }

    
}

BeSpokedSalesApp/Controllers/ProductController.cs
using BeSpokedSalesApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using BeSpokedSalesApp.Common;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BeSpokedSalesApp.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly ApiClient<Product> _apiClient;
        private readonly string _apiEndpoint;
        public ProductController(ILogger<ProductController> logger, ApiClient<Product> apiClient)
        {
            _apiClient = apiClient;
            _logger = logger;
        }

        public async Task<IActionResult> Products()
        {
            var products = await _apiClient.GetAsync("products");
            var viewModel = new ProductListModel { Products = products };
            return View(viewModel);
        }

        public async Task<IActionResult> UpdateProduct(int id)
        {
            var product = await _apiClient.GetByIdAsync("Products", id);
            ProductEditModel viewModel = new ProductEditModel()
            {
                Product = product
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateProduct(int id, [Bind("ProductId,Name,Manufacturer,Style,PurchasePrice,SalePrice,QtyOnHand,CommissionPercentage")] Product product)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }
            ProductEditModel viewModel = new ProductEditModel()
            {
                Product = product
            };

            if (ModelState.IsValid)
            {
                try
                {
                    await _apiClient.PutAsync("Products", id, product);
                }
                catch (Exception)
                {
                   throw;
                }
                return RedirectToAction("Products");
            }
            return View(viewModel);
        }
    }

    
}

BeSpokedSalesApp/Controllers/SaleController.cs
using BeSpokedSalesApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using BeSpokedSalesApp.Common;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BeSpokedSalesApp.Controllers
{
    public class SaleController : Controller
    {
        private readonly ILogger<SaleController> _logger;
        private readonly ApiClient<Sale> _apiClient;
        private readonly ApiClient<Salesperson> _apiClientSalesperson;
        private readonly ApiClient<Product> _apiClientProduct;
        private readonly ApiClient<Customer> _apiClientCustomer;
        private readonly string _apiEndpoint;
        public SaleController(ILogger<SaleController> logger, ApiClient<Sale> apiClient, ApiClient<Salesperson> apiClientSalesperson,
            ApiClient<Product> apiClientProduct, ApiClient<Customer> apiClientCustomer)
        {
            _apiClient = apiClient;
            _apiClientCustomer = apiClientCustomer;
            _apiClientProduct = apiClientProduct;
            _apiClientSalesperson = apiClientSalesperson;
            _logger = logger;
        }

        //public async Task<IActionResult> Sales()
        //{
        //    var Sales = await _apiClient.GetAsync("Sales");
        //    var viewModel = new SaleListModel { Sales = Sales.ToList() };
        //    return View(viewModel);
        //}

        public async Task<IActionResult> Sales(DateOnly? startDate, DateOnly? endDate)
        {
            var Sales = await _apiClient.GetAsync("Sales");

            if (startDate.HasValue && endDate.HasValue)
            {
                Sales = Sales.Where(s => s.SalesDate >= startDate && s.SalesDate <= endDate).ToList();
            }

            var viewModel = new SaleListModel { Sales = Sales.ToList() };
            return View(viewModel);
        }

        public async Task<IActionResult> CreateSale()
        {
            SaleCreateModel viewModel = new SaleCreateModel();
            var Products = await _apiClientProduct.GetAsync("products");
            var Salespersons = await _apiClientSalesperson.GetAsync("Salespeople");
            var Customers = await _apiClientCustomer.GetAsync("customers");
            viewModel.Salespersons = Salespersons != null ?  Salespersons.ToList() : new List<Salesperson>();
            viewModel.Products = Products != null ? Products.ToList() : new List<Product>();
            viewModel.Customers = Customers != null ? Customers.ToList() : new List<Customer>();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateSale(Sale Sale)
        {
            if (ModelState.IsValid)
            {
                await _apiClient.PostAsync("Sales", Sale);
                return RedirectToAction("Sales");

            }
            else
            {
                SaleCreateModel viewModel = new SaleCreateModel()
                {
                    Sale = Sale
                };
                var Products = await _apiClientProduct.GetAsync("products");
                var Salespersons = await _apiClientSalesperson.GetAsync("Salespeople");
                var Customers = await _apiClientCustomer.GetAsync("customers");
                viewModel.Salespersons = Salespersons != null ? Salespersons.ToList() : new List<Salesperson>();
                viewModel.Products = Products != null ? Products.ToList() : new List<Product>();
                viewModel.Customers = Customers != null ? Customers.ToList() : new List<Customer>();
                return View(Sale);
            }
            
        }
    }

    
}

BeSpokedSalesApp/Controllers/SalesPersonController.cs
using BeSpokedSalesApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using BeSpokedSalesApp.Common;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BeSpokedSalesApp.Controllers
{
    public class SalesPersonController : Controller
    {
        private readonly ILogger<SalesPersonController> _logger;
        private readonly ApiClient<Salesperson> _apiClient;
        private readonly string _apiEndpoint;
        public SalesPersonController(ILogger<SalesPersonController> logger, ApiClient<Salesperson> apiClient)
        {
            _apiClient = apiClient;
            _logger = logger;
        }

        public async Task<IActionResult> Salespersons()
        {
            var salespersons = await _apiClient.GetAsync("Salespeople");
            var viewModel = new SalespersonListModel { Salespersons = salespersons };
            return View(viewModel);
        }

        public async Task<IActionResult> UpdateSalesPerson(int id)
        {
            var salesperson = await _apiClient.GetByIdAsync("Salespeople", id);
            var salespersons = await _apiClient.GetAsync("Salespeople");
            SalespersonEditModel viewModel = new SalespersonEditModel()
            {
                Salesperson = salesperson,
                Managers = salespersons.ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateSalesPerson(int id, Salesperson salesperson)// [Bind("SalespersonId,FirstName,LastName,Address,Phone,StartDate,TerminationDate,CommissionPercentage,ManagerId")] Salesperson salesperson)
        {
            if (id != salesperson.SalespersonId)
            {
                return NotFound();
            }
            var salespersons = await _apiClient.GetAsync("Salespeople");
            SalespersonEditModel viewModel = new SalespersonEditModel()
            {
                Salesperson = salesperson,
                Managers = salespersons.ToList()
            };

            if (ModelState.IsValid)
            {
                try
                {
                    await _apiClient.PutAsync("Salespeople", id, salesperson);
                }
                catch (Exception)
                {
                   throw;
                }
                return RedirectToAction("Salespersons");
            }
            return View(viewModel);
        }
    }

    
}

BeSpokedSalesApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BeSpoked Bikes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BeSpokedSalesApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Product" asp-action="Products">BeSpoked Bikes</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesPerson" asp-action="Salespersons">Sales Persons</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Products">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Customers">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Sales">Sales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SalesCommissionReport" asp-action="Report">Reports</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BeSpokedSalesApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>